core: assert CFG_VIRTUALIZATION=y and CFG_ARM32_core=y are exclusive
As for current implementation, CFG_VIRTUALIZATION=y is not supported
in 32bit OP-TEE core (CFG_ARM32_core=y). Actually build fails with
error trace like below:

core/arch/arm/mm/core_mmu_lpae.c:432:2: error: implicit declaration of function ‘write_ttbr0_el1’; did you mean ‘write_ttbr1’? [-Werror=implicit-function-declaration]
  write_ttbr0_el1(ttbr | ((paddr_t)prtn->asid << TTBR_ASID_SHIFT));

This change ensures a nice error trace is displayed instead:

mk/config.mk:492: *** CFG_ARM32_core is set to 'y' (from file) but its value must be 'n'.  Stop.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>