scmi-server: module psu: fix missing switch default case
Fix build issue reported by GCC:

core/scmi-server/SCP-firmware/module/psu/src/mod_psu.c: In function ‘mod_psu_process_bind_request’:
core/scmi-server/SCP-firmware/module/psu/src/mod_psu.c:349:5: error: switch missing default case [-Werror=switch-default]
     switch (fwk_id_get_api_idx(api_id)) {
     ^~~~~~

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>